### ISSUE TITLE
Unable to upload multiple files into ctmmweb

### ISSUE THREAD

**Issue by ofmerrit** [ctmm-initiative/ctmmweb#126]
I am doing a project on birds and have successfully uploaded individual files to get the home ranges but cannot upload multiple files to see the overlap of home ranges for multiple individuals.  When I try to add two or more zip files (saved from ctmm web previously) to restore progress, the site starts to load but then fails and says unable to connect to server.

**Comment by xhdong-umd** [comment]
Uploading multiple files are only designed for multiple location input files. 
The zip saved from ctmmweb are session restoration file. The app cannot take multiple session restoration file because there will be conflicts in everything.

If you want to see overlap of home range for multiple individuals, you have to load all the individuals in one session.

**Comment by ofmerrit** [comment]
Thank you for you comment, but I should have clarified.  I have also tried uploading multiple new files into one session, but if I upload one file and then another one, the second file just overlaps the first and data only comes up for the second file.  Do I need to upload solely one file that has all the data for every individual?

**Comment by xhdong-umd** [comment]
You can upload multiple files, but you have to drag all of them and drop to the upload box in one action, or use the browser dialog to select multiple files(which will be limited in same folder by file open dialog design). Or you can zip multiple files together.

You cannot upload one file A then upload one file B and expect them being merged, because it's totally possible some user just want to use B to replace A. If the app stay in a "merge mode", any new upload will get merged and there will not be new session.

**Comment by ofmerrit** [comment]
I tried dragging all of them and it said error in import, check data again.  But all of these files individually work.  What should I do next?

**Comment by xhdong-umd** [comment]
Is there any more detail in error message? Especially in R console. Please post the full error/warning messages.

**Comment by ofmerrit** [comment]
How do I get to the R console from this website? https://ctmm.shinyapps.io/ctmmweb/
Thank you.

**Comment by xhdong-umd** [comment]
For hosted app, if the app didn't crash, you can click `Diagnostic Info` button on left side bar (it's on the bottom), or click `download report` in first box of first page.

**Comment by xhdong-umd** [comment]
Closed for no new updates.

**Comment by ofmerrit** [comment]
Alright, so I was able to upload one CSV that I downloaded from Movebank, and the data showed up on the ctmm site. However, I clicked on the home range tab so that I could see the home ranges and subsequently the overlap, but those sections don't have anything in them. I have attached a screenshot of what I see. Is there anything I can do to fix this?

<img width="960" alt="2020-12-15" src="https://user-images.githubusercontent.com/70243782/102284653-89d73900-3f02-11eb-946a-2eafa2748b63.png">

**Comment by NoonanM** [comment]
If you did not encounter any error messages, the likely reason is that the models have not yet been fit to the data. In order to see home ranges you need to select the individuals you're interested in working with, fit their movement models on the model selection page, and then estimate the home ranges. Note, the model fitting step can be slow especially with large datasets, so the application will not display anything until they have been fit.
