### ISSUE TITLE
Select all after use of search

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmmweb#46]
When searching within loaded individuals, one should be able to select all individuals based on the search results.

**Comment by xhdong-umd** [comment]
If you filtered the individuals by inputing in the search field, the app will update to the filtered results, which is just like all results have been selected. 

The only difference is that if the results is more than 1 page and only current page is shown. But you can change the page length to up to 20.

To make the select all button work with search result is doable, I just think the current behavior worked for the purpose already. 

Or is there anything you think not covered yet with this?

**Comment by vestlink** [comment]
I see what you mean.

The functionality of the app is correct.

It's just from a users point of view and the logic of the app.

It might just be me, but when i search for something I maybe wan't to eventually select the search result as a whole.

But the app in itself behaves nicely.

**Comment by xhdong-umd** [comment]
Yes, the app actually take current page as "selected" if no rows are explicitly selected. This is mentioned in help but may not be obvious to users.

I realized that could be one scenario an explicitly selection is useful: user can filter the individuals, select them with the button, then clear the filter and still keep the selection. Now it's easy to see which are selected and which are not. The dynamic filtering works great for fast checking, but it will become lost after the filter is cleared.

I have updated the app so that `select all` button work on filtered rows.
