### ISSUE TITLE
Movebank marked outliers

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#47]
"points we had marked in movebank as 'manually marked outliers' are showing up in the app when we load directly from MB using your app."

I think there should be a checkbox option when importing Movebank files "include outliers" that is FALSE by default.

**Comment by xhdong-umd** [comment]
The download from MoveBank inside app used the MoveBank API, which only download several core columns by default. This is mentioned in the help page for the box "selected study details". It's possible to ask for more columns but you need to know it's available for the data first, then assemble a specific request. 

I considered to check what columns are available and assemble a specific request based on that, but the combination seemed quite overwhelming. See [how many possible attributes are available](https://github.com/xhdong-umd/movebank-api-doc/blob/master/document/all_attributes.md). And you need different syntaxes for different combinations which are not really documented, I have to learn through trials and that's why I summarized my findings into a document.

> some call only need one parameter of entity_type, some will need to add study_id, some will need tag_study_id instead of study_id, some will need to add sensor_type_id

Also checking every possible column could be bad for server performance, and I think the best method is just to get the csv that available to users in regular download. I used to find some hack that get that csv but it doesn't always work. I asked them about providing the csv in API, they said they had meetings discussed some of my suggestions but I don't know any update yet.

That's why I added a link to open the study page directly, to save some work for user to download the csv in the regular method.

**Comment by chfleming** [comment]
Ah, for some reason I thought the API had been updated.
