### ISSUE TITLE
Support for dt and weights

### ISSUE THREAD

**Issue by kjklauder** [ctmm-initiative/ctmmweb#54]
It would be awesome to have support for the "dt=" and "weights=" arguments, as outlined in the vignettes.

**Comment by chfleming** [comment]
I assume you are talking about the `dt` argument of `variogram()` and the `weights` argument of `akde()`. I think that's a good idea with the weights paper out now.

`variogram` `dt` is straightforward enough to implement, though requires some explaining. `akde` `weights=TRUE` has a lot of tuning options described in `help('bandwidth')` and sometimes requires picking the right options to get good performance/accuracy.

**Comment by kjklauder** [comment]
Yes that is what I was referring to. I see your point about the complexity of 'bandwidth' options. Would it be possible to have a toggle option for 'weights' that defaults to FALSE, but if TRUE is selected, expands to show additional tuning options? That would keep things streamlined for those uninterested in those arguments.

**Comment by xhdong-umd** [comment]
- For `dt`, I think we can just add a text field for input, and a list of time units in this box. The text field can take a series numbers separated by comma. I'll also link to the vignettes `Irregular Sampling Schedules` section in the help.

<img width="710" alt="screen shot 2018-03-16 at 4 37 27 pm" src="https://user-images.githubusercontent.com/25039897/37543597-7e57cf28-2938-11e8-8cf3-0446a4de3eef.png">

- For `weights`, the simplest way is just to add a checkbox in home range page, though that will apply to all selected animals. It's also possible to make a multiple choice selection box to turn it on for some animals individually.

  I'm not sure if the actual usage need more detailed control, and if it's practical to implement all the options.

**Comment by NoonanM** [comment]
`weights` can be slow for some datasets, and is not always needed. I think the best option would be to be able to turn it on for some animals individually.

**Comment by xhdong-umd** [comment]
When you add `dt` for variograms, do you also need to apply it to the modeling process?

**Comment by chfleming** [comment]
`variogram()` `dt` is specifically for the variogram calculation. `ctmm.fit()` is totally robust to sampling irregularity and does not have nor need a `dt` argument.

**Comment by xhdong-umd** [comment]
When I tested with `gazelle` data, I met some errors because there is no timestamp columns and my code was expecting them. Is this normal? Should the app take this kind of data?

**Comment by chfleming** [comment]
The `variogram` `dt` example in the vignette is with a gazelle and works for me.
Where were the errors?

**Comment by xhdong-umd** [comment]
The vignette code works fine. I wanted to test the dt feature in app with gazelle data, so I need to merge telemetry object into data.frame. 

Previously all input data went through as.telemetry have long/lat, timestamp, x, y, t columns, and I rely on timestamp column to calculate the sampling start/end time. The gazelle data only has x, y, t columns, so my code met error here. I think maybe this is a special case and the app don't need to take this kind of data?

Is there any other movebank format data that can test with various dt?

**Comment by chfleming** [comment]
The gazelles and wolves in the package are anonymized and lack long-lat & timestamp data. You don't need to code for these kinds of data to work.

To test `variogram()` `dt`, I think the buffalo Pepper has both 1-hour and 2-hour sampling.

Instead of calling the `dt` box "Irregular Sampling Schedules" I would call it "Multiple Sampling Schedules".

Should we annotate the titles of AKDEs with optimal weights?

**Comment by xhdong-umd** [comment]
I just realized there are two more issues with `dt`.

1. Can we detect the multiple sampling schedule and get them automatically?
2. The sampling schedule may be animal specific, right? So we need to apply it to individual animals?

**Comment by chfleming** [comment]
1. Conceivably, but its not trivial.
2. This can happen, yes. Being able to apply to all and to individuals would probably be useful.

**Comment by xhdong-umd** [comment]
The UI above is just the user interface, I'm still in the process of implementing the functions.

@jmcalabrese @chfleming @NoonanM These two feature looks trivial at first, but it turned out they may need some substantial changes in app logic.

In Shiny you can update data according to user input with two approaches:
- automatic update triggered by any change in dependent variables. This is implemented as reactive expression. For now most updates in app are implemented this way, for example the home range plot depend on 
  - modeling data
  - multiple plot control options
Any change in above will redraw the plot.
- manual update triggered by an event, typically a button click. This is implemented as event observer and reactive value. If you want to modify a value in several different places(for example, a button click modify something, another separate event also modify the same value), this is the only method. The automatic update method above cannot be modified manually.

The home range calculation is an automatic updating reactive expression. Now the `dt` input can be added to the automatic expression, the only problem is that when user was adding multiple selections, every one step in the process will trigger the update, so the home range calculation will run in every step, which can take too much time.

The visualization page have same design: if you select rows in the data summary table, even if you plan to select 3 rows, the 3 clicks will trigger changes 3 times, so the first 2 changes are wasted. This is not a big problem for visualization since the update is not too slow, but it will be a problem for home range calculation. The calculation cache doesn't help either since the calculation take the whole list as input, and partial change in the list means cache cannot be used.

There is no way to avoid this in the automatic update design: the app have no way to know if a row selection is the final update user want or just in the middle of series selections, it has to update according to every change.

To avoid the extra calculation in home range with `dt`, we need to switch to manual update. There could be a button `estimate home range`, and the calculation only begin with the button click. Now user can add all the `dt` choices, click the button to update home range.

**Comment by xhdong-umd** [comment]
The change above is still doable, but I'm not sure if it worth the effort, considered that `weights` is complex, with lot of tuning options difficult to implement in app (the options are more suitable for command line instead of web app), and it can be slow and not always needed.

**Comment by xhdong-umd** [comment]
I tried to detect the multiple sampling schedule, at least give user a histogram to show which animal have multiple sampling schedule. It's indeed not easy. 

`Pepper` have these schedules:

<img width="755" alt="screen shot 2018-04-13 at 10 05 11 am" src="https://user-images.githubusercontent.com/25039897/38739192-2e21d578-3f02-11e8-91fa-795c84928bde.png">

The histogram is difficult to read. There are too many irregular values (the data below have been rounded, otherwise it's messer), even the majority are 1, 2 hours. That is not obvious from the histogram plot because the axis is stretched too much by the big numbers.

```
> table(intervals)
intervals
  0   1   2   3   4   5   6   7   8  10  12  14  16  18  20  22  24  26  28  30  34  36  40  42  46  48 
  3 570 796  15  95   4  74   1  43  23  26  12   7   8   8   8   3   4   3   1   5   4   2   2   1   1 
 52  74  84 112 122 
  1   1   1   1   1 
```

So I have to assume user know the value and skip the idea of histogram.

**Comment by xhdong-umd** [comment]
I noticed previously I had a plan to implement `dt`, `res`, `error` of `variogram` and pool variograms.

<img width="712" alt="screen shot 2018-04-13 at 10 44 07 am" src="https://user-images.githubusercontent.com/25039897/38741299-a46c96f0-3f07-11e8-9890-523746c6c9e3.png">

It's better that all variogram related new features can be considered together in a consistent way.

- The error part is another important and complex topic that covered several aspects, let's put it aside for now.
- Do we also need the `res` parameter and pool variograms?
- `dt` itself may need quite some space already. We need to specify animals, sample schedules numbers, units, and the whole page may need different treatments for different animals.

**Comment by xhdong-umd** [comment]
I used 1, 2 hours for Pepper variogram.  In the vignette example the variogram with dt is much more smoother, but here it's not that obvious. Is the result correct?

```r
pepper <- buffalo[[4]]
dt <- c(1,2) %#% "hour"
plot(variogram(pepper))
```
<img width="777" alt="screen shot 2018-04-13 at 11 00 42 am" src="https://user-images.githubusercontent.com/25039897/38742297-270df764-3f0a-11e8-87c3-1ba19a90290d.png">


```r
plot(variogram(pepper, dt = dt))
```

<img width="755" alt="screen shot 2018-04-13 at 11 00 53 am" src="https://user-images.githubusercontent.com/25039897/38742305-2b3e51f8-3f0a-11e8-9430-57320b3e8251.png">

**Comment by chfleming** [comment]
Yeah, Pepper is not a very stark example like the gazelles. You could do some subsampling of any regularly sampled dataset to get the same effect, like

`SUB <- c(1,2,3,4,5,10,11,12,13,14,15,20,21,22,23,24,25,30)`

As for the other variogram options, I think `dt` is probably the most used.

**Comment by xhdong-umd** [comment]
`dt` is done, though I don't have a good data to test it yet. I tried subsampling but didn't have any obvious result.

Select animals, input intervals

<img width="706" alt="screen shot 2018-04-18 at 10 52 45 am" src="https://user-images.githubusercontent.com/25039897/38939881-de407d54-42f6-11e8-9d23-a7df9dbb783d.png">

Click `Add` button, it will be added to a list, and variogram updated. So you can add multiple schedules for multiple individual groups.

<img width="699" alt="screen shot 2018-04-18 at 10 53 05 am" src="https://user-images.githubusercontent.com/25039897/38939913-f8bbd3c2-42f6-11e8-8b91-c93084ecf6a5.png">

The variogram dt call is really simple in ctmm, but to add an UI to input flexible paramters (with any animal, value, unit combination) and plug in current workflow is not trivial.

**Comment by xhdong-umd** [comment]
For home range, we are using `akde(telemetry_list, CTMM_model_list)` to make sure they are in same grid. Can we turn on some individuals `weight` specifically in this?

**Comment by xhdong-umd** [comment]
I added a line in variogram title if `dt` is used so that it's easier to read the plot.

<img width="705" alt="screen shot 2018-04-24 at 1 11 43 pm" src="https://user-images.githubusercontent.com/25039897/39202830-1c211b32-47c1-11e8-9ba4-87013e658bdf.png">


The weight feature will need `akde` to take a logical vector for list inputs.

**Comment by chfleming** [comment]
`akde` can take now an array of `weights` matching the list length of the data and model arguments.

Those `dt` variograms look really weird. I'm going to take a look at that next.

**Comment by xhdong-umd** [comment]
It's possible just because I used sampled data (100 points). I'll try full data tomorrow, and if the result is same I'll generate some reproducible code for you.

**Comment by xhdong-umd** [comment]
Yes, the plot above is caused by the small sample of data. This is same parameters on the normal data set

<img width="699" alt="screen shot 2018-04-25 at 9 55 10 am" src="https://user-images.githubusercontent.com/25039897/39250451-d4d075e4-486e-11e8-86b6-73f95d7ecb27.png">

**Comment by xhdong-umd** [comment]
For pooled variograms, I think in last meeting you said the pool variogram should replace individual variograms instead of an additional one. For example if we pool Cilla and Gabs, we should remove Cilla, Gabs and add pool of Cilla Gabs.

I'm wondering if user may have the need to try different combinations. For example first create a pool of Cilla, Gabs, then create a pool of Gabs, Toni. And do you think it's useful to compare the individual variogram and the pooled one to see difference?

If we just add the pool as additional variogram, it'll be easy to compare with the individual ones, and it'll also easy to implement different combinations. Otherwise if a pool replaced some individuals, the individuals cannot be used for another pool unless I specifically maintain another list of original variograms. That's still doable just with more complexity, and I'm wondering if adding pool as additional has more advantages.

**Comment by chfleming** [comment]
I wouldn't worry about visual comparison, as most people will only pool when the individual variograms look bad.

For more flexibility, I suppose you could have one selection of the individuals for the pool copied over (by default) to a second selection of individuals whose variograms will be overwritten by the pooled variogram. That way you could deselect some of the better individuals to keep their individual variograms.

**Comment by xhdong-umd** [comment]
weights parameter is implemented. The plot titles are marked for easier identification, but I didn't change the home range summary table because I didn't find an easy way to add information without clutter. I suppose the plot title changes should serve the purpose.

<img width="691" alt="screen shot 2018-04-25 at 11 47 51 am" src="https://user-images.githubusercontent.com/25039897/39257054-875f01ee-487e-11e8-8453-928d1b95a910.png">

**Comment by chfleming** [comment]
Would it be worth saving space by noting the weighted AKDEs with the balance emoji unicode (or Libra symbol) in the title, instead of the second line of text in the title?

**Comment by xhdong-umd** [comment]
The balance icon in the app is fa awesome icon. Is there a unicode symbol can be used for similar purpose?

For the Libra symbol <img width = "20" src = "https://www.fileformat.info/info/unicode/char/264e/libra.png">, I'm not sure if that symbol is intuitive enough for users. I didn't recognize this symbol before searching on it.

**Comment by chfleming** [comment]
2696

**Comment by xhdong-umd** [comment]
It doesn't print correctly with this code

```r
# some symbol work
plot(1, xlab='\u0298')
# but scale symbol is not printing correctly
plot(1, xlab='\u2696')
```

**Comment by chfleming** [comment]
"\U2696" on the command line and in the `title()` command works for me in Ubuntu.

**Comment by xhdong-umd** [comment]
Yes it's platform dependent. 

[Fonts supporting 2696 ](http://www.fileformat.info/info/unicode/char/2696/fontsupport.htm)

From the list I guess linux and windows should have it but not for mac.

**Comment by chfleming** [comment]
Is the Libra symbol supported on Mac?

If so, I suppose we could detect OS and then do scales on Linux/Windows and Libra on MacOS, matching consistency with the selection box.

**Comment by xhdong-umd** [comment]
Libra can be print in rstudio console but not in plot.

Fonts could be complex as different linux distributions actually can have different default fonts. See discussions [here](https://bmb-common.blogspot.com/2011/05/unicode-symbols-in-r.html).

When we are saving plot into pdf and png, it can bring more problems further since they are another platform...

**Comment by NoonanM** [comment]
Looking around, it doesn't seem like there's a simple solution for plotting unicode symbols on mac.

**Comment by xhdong-umd** [comment]
When you pooled some variograms like "Cilla, Gabs", and only the pooled variogram is shown, what should we do with the `ctmm.guess` values? Previously it was `ctmm.guess` applied to every telemetry object. 

I think we still need to apply `ctmm.guess` to individual telemetry object, then we still need to show individual variograms in guesstimate tab? So maybe we just ignore the pooled variograms in guesstimate and modeled tabs?

**Comment by xhdong-umd** [comment]
Compare to a separate tab, adding pooled variogram to individual variograms will be simpler in UI. By keeping individual variograms intact, put pool variograms into pure additional plot, the original work flow can be maintained without much change.

**Comment by chfleming** [comment]
The `ctmm.guess` value would get duplicated, but its value is needed for the individuals' `ctmm.fit` call, and then again to compare against the result of `ctmm.fit` on the individual.

What's the difficulty in simply replacing the individual's variogram with the pooled variogram? Then each individual has one variogram.

**Comment by xhdong-umd** [comment]
If we replace each individual's variogram with the pooled, does that mean a pooled 3 variograms will be plot 3 times?

**Comment by xhdong-umd** [comment]
So with pooled variogram we are supposed to also supply that pooled variogram to `variogram` parameter in `ctmm.guess` call?

`ctmm.guess(data,CTMM=ctmm(),variogram=NULL,name="GUESS",interactive=TRUE)`

**Comment by chfleming** [comment]
Yes, yes, and yes.

**Comment by xhdong-umd** [comment]
I found it's quite cumbersome to maintain correct plot titles when tab 1 removed the duplicates in pooled variogram, and other tabs keep one copy for each individual in the pool. 

Since tab 2 and 3 already are showing individual copy of the pooled variogram, if we use same arrangement in tab 1, it'll be much easier to implement, also be consistent in UI, probably less surprises for users.

**Comment by xhdong-umd** [comment]
Now the plot title can show any combination of multiple sampling schedule/pool variogram in 3 tabs. The 1st tab also show each individual variogram for pool variogram, same with other tabs.

**Comment by xhdong-umd** [comment]
`ctmm.guess` is taking the updated variogram (multiple schedule, or pooled) as parameter now. The dt, weights, pool variogram features are finished.

**Comment by xhdong-umd** [comment]
Thinking again, we need to present the kmeans result, which may be best represented in the original format. So maybe just using seconds will be simple and consistent. I'll implement the feature first to see how it works, and adjust the units later.

**Comment by xhdong-umd** [comment]
If we label the kmeans center in the histogram, it should be easier to read and there is no need for an additional table of kmeans result.

I have to use a package `ggrepel` to avoid label overlap though.

<img width="790" alt="screen shot 2018-08-28 at 5 33 43 pm" src="https://user-images.githubusercontent.com/25039897/44752286-8b3d8700-aae8-11e8-85e3-f4a92db1033d.png">

**Comment by xhdong-umd** [comment]
I implemented the kmeans feature roughly. If user click a checkbox, the multiple schedule box will extend with more controls:

### table and histogram

- a histogram of time intervals, and a table showing running kmeans on each individual. the table will show kmeans result, k value, also the kmeans result will be marked in histogram.

- By default 5% outlier in intervals are filtered out, and there are 7 bins in histogram, these can be adjusted with sliders.

<img width="633" alt="screen shot 2018-09-05 at 3 40 25 pm" src="https://user-images.githubusercontent.com/25039897/45119480-94060c80-b129-11e8-86c6-612c84ac73b5.png">

<img width="635" alt="screen shot 2018-09-05 at 3 40 38 pm" src="https://user-images.githubusercontent.com/25039897/45119504-a08a6500-b129-11e8-8967-28febe70c96c.png">

----------------------------------------------------------
### change k

- Selecting rows in the kmeans result table, then adjusting slider `k` will change k for those rows.
- Sometimes kmeans will report error "more cluster centers than distinct data points.", which is normal given certain parameter combinations.

<img width="630" alt="screen shot 2018-09-05 at 3 40 56 pm" src="https://user-images.githubusercontent.com/25039897/45119514-a718dc80-b129-11e8-9b00-5e427fa998de.png">

<img width="631" alt="screen shot 2018-09-05 at 3 41 20 pm" src="https://user-images.githubusercontent.com/25039897/45119522-aed88100-b129-11e8-80d3-b6e59852e949.png">

**Comment by xhdong-umd** [comment]
I used a slider to change k for selected individuals. However when user is dragging a slider, the intermediate values could be output as the computer will not know if that's some intermediate value in dragging or the value user want. This means if user is dragging slowly from 1 to 5, the value 2, 3, 4 could be output in the process.

Each new k value will trigger changes in the kmeans result table, which in turns reset the row selection, so the later values will not work when there is no row selected.

An alternative is to use numeric input, which can be used to input the value directly. If user do use the arrow in the input box, similar thing will happen if user increased from 1 to 5 step by step, but it's more understandable that each click count for one change.

I plan to change the slider to the numeric input.

<img width="210" alt="screen shot 2018-09-06 at 3 12 04 pm" src="https://user-images.githubusercontent.com/25039897/45179695-3e903500-b1e7-11e8-905f-9003612ed913.png">

**Comment by xhdong-umd** [comment]
The table and plot now have the values converted to better unit

<img width="643" alt="screen shot 2018-09-07 at 4 44 28 pm" src="https://user-images.githubusercontent.com/25039897/45242272-60f48200-b2bd-11e8-886b-41f828e0b937.png">

**Comment by xhdong-umd** [comment]
@chfleming I experimented with `kGmedian` in package `Gmedian`, but cannot make it work with 1-dimensional data. I searched but cannot find any example discussing this.

```r
>   x <- matrix(diff_t, ncol = 1)
>   cl <- Gmedian::kGmedian(x, ncenters = 2)
Error in stoKmed_rcpp(x0, X, centers, gamma = gamma, alpha = alpha) : 
  Not a matrix.
```

**Comment by chfleming** [comment]
It looks like the R package Ckmeans.1d.dp can do k-median clustering and select k via BIC given a range of k values to select from. k selection should help avoid the redundant cluster estimates.

**Comment by xhdong-umd** [comment]
This function works but I'm not seeing the effect of ignoring outliers. With Pepper in buffalo, k = 2, this is result I got

`cl <- try(Ckmeans.1d.dp::Ckmedian.1d.dp(na.omit(diff_t), k))`

<img width="594" alt="screen shot 2018-09-10 at 12 01 36 pm" src="https://user-images.githubusercontent.com/25039897/45309255-54f10600-b4f1-11e8-8d84-f98c2c575a73.png">

It still put the outliers into a cluster of size 166, and the remaining points into one cluster of size 1588 with center 7200.

<img width="476" alt="screen shot 2018-09-10 at 12 03 41 pm" src="https://user-images.githubusercontent.com/25039897/45309601-06903700-b4f2-11e8-8093-f105e2408c03.png">


I tried to give k = 3 and hope that outliers will take one cluster, and we get the other 2 real clusters at 3600, 7200. Still, outliers were split into 2 clusters, with most values still in one cluster.

<img width="581" alt="screen shot 2018-09-10 at 12 07 38 pm" src="https://user-images.githubusercontent.com/25039897/45309653-24f63280-b4f2-11e8-92b9-706c2c3b1b2e.png">


<img width="556" alt="screen shot 2018-09-10 at 12 07 18 pm" src="https://user-images.githubusercontent.com/25039897/45309638-1a3b9d80-b4f2-11e8-81c4-1e1f02ab7855.png">

**Comment by NoonanM** [comment]
At some point can you add a feature to turn weights on in the home range estimation for all individuals at once?

**Comment by xhdong-umd** [comment]
I added a checkbox to select all individuals. You still need to click `apply` button, but I think this is useful as you can select all then remove some of them.

<img width="640" alt="screen shot 2018-09-13 at 10 15 31 am" src="https://user-images.githubusercontent.com/25039897/45493955-fc627880-b73d-11e8-9110-0d394c9ce249.png">

**Comment by NoonanM** [comment]
The ggrepel package is not automatically downloaded with the package.

**Comment by xhdong-umd** [comment]
Thanks, I just added it and updated the package
