### ISSUE TITLE
Help text

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#61]
On the model selection page, it would be useful to include definitions of the parameters (e.g., tau_position, tau_velocity, etc...) under the `?help` button.

Related to this, it might also be useful if each of the help files linked to the appropriate publications describing the methods so users can read up on things they're not familiar with.

Sorry for opening up so many issues in a row...

**Comment by xhdong-umd** [comment]
No problem, we will just deal with the issues one by one.

As for help text, they are all plain markdown files under [this folder](https://github.com/ctmm-initiative/ctmmweb/tree/package/inst/app/help). You can add links, embed pictures if you want. Chris mentioned that the variogram part need more detailed help with pictures, we haven't get time to do it yet.

Usually I'll link to the related ctmm method help, and there will be references in ctmm help (this page was not updated yet since it was finished a long time ago).

I'll look at this when all the other more important tasks are finished. At the same time, feel free to edit any help text for any problem you saw. There are probably some errors/non accurate descriptions around.

I think github usually allow you to click `edit` button, which will ask you to fork the repo in your own account, then make changes, commit and make pull request. This process is a little bit complex though, so you can also just write any change you want here and I'll incorporate them.

**Comment by xhdong-umd** [comment]
I added some reference to the variogram vignette and certain ctmm functions help page. 

I think it might be difficult to explain everything in the help, when the concepts might be best learned from the complete vignette. Of course some simple definitions could be helpful, but I'm not sure I can write them accurately. Please feel free to edit the text or post changes you want here.

**Comment by NoonanM** [comment]
Definitely focus on the other tasks first.

When I have some time I'll have a look at the text files and see if there is anything I can add, without making the help bubble too large.

**Comment by xhdong-umd** [comment]
All paper references given by @NoonanM have been added to help pages.  I also linked them to the doi url. 

Note the app launched in RStudio may not allow to click external links, you have to right click on the link and select "open link in browser".
