### ISSUE TITLE
Loading data from Movebank

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#66]
This is forwarded from an email:

> Just a quick question: is there a known error with ctmm being able to load data from movebank right now?  I have tried running the web app and also locally from R studio, and after logging no data from movebank is being displayed.  Just last week or so I was able to access the Harlequin frog data on movebank.  I attached a couple images for reference.

<img width="640" alt="screen shot 2018-06-03 at 5 23 49 pm" src="https://user-images.githubusercontent.com/19801979/40891460-e3f81d8e-6753-11e8-9804-af1cd9f17a1d.png">
<img width="640" alt="screen shot 2018-06-03 at 5 24 18 pm" src="https://user-images.githubusercontent.com/19801979/40891461-e40d89b2-6753-11e8-85cd-a4f0f5ca4369.png">

**Comment by xhdong-umd** [comment]
The bug was caused by a change in column types. 

Previously `i_can_see_data` is read as character, now it's read as logical. It could be newer version of `data.table` changed behavior, or movebank data is more consistent so there is no need to bump column type from logical to character(so it can cover the more irregular input like "", "none" etc).

I have fixed the problem, updated the package and hosted app. I also specified the column type to avoid similar problem appear again in future.

**Comment by xhdong-umd** [comment]
It's reported the direct import of movebank data has some problem too. I found the previous update of importing multiple files changed a function behavior, and the direct import need to be updated to be compatible.

It has now been fixed.
