### ISSUE TITLE
Potential Feature: Subset by area

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#70]
I'm currently working on some data where it would be useful to select points clustered in an area. These are migratory animals that exhibit home range behavior on each end of the migration. When collected over multiple years, you get data where the animal is in the same place year after year, but it's impossible to subset that by time since it comes in multiple time blocks. Currently, you can kind of get at this in a hacky way by selecting clusters based on distance from centre in the outlier detection page, but it's not very clean. I imagine that this use case would be common for anyone working with migratory animals.

**Comment by xhdong-umd** [comment]
In visualization page, I can try to add a button so that when you draw a box in location plot then click that button it should crop the data, add a `Cilla_crop1` data set to existing data set (so that original data is not modified).

@chfleming @jmcalabrese What do you think about this?

**Comment by NoonanM** [comment]
That would be perfect.

**Comment by xhdong-umd** [comment]
It's not as simple as it looks.

- I would prefer to generate a subset, add as additional data set instead of modifying current data, just like how time subsetting works.
- with multiple individuals showed, a crop box can have impact to multiple individuals. Then we need to create subset for every individual and add all of them. I think that may not be what user want.

For the use case can we assume user always work on single individual? Then it will have same requirement like time subsetting page. And we can move the button to time subsetting page since it has the requirement already. In that case the page name may need to change to something like "subsetting".

**Comment by xhdong-umd** [comment]
@jmcalabrese @chfleming Do you think it's a good idea to add a "subset data by draw a box in location plot" in time subsetting page? and rename the page to something like "subsetting"?

**Comment by xhdong-umd** [comment]
I found it's actually easier to put the location subset in separate page. The time subsetting page have its own workflow, especially you can add multiple time segments and combine to one subset. It's difficult to insert a location subset in this workflow without confusion.

**Comment by xhdong-umd** [comment]
I implemented the feature in the visualization page. You need to select single individual, then draw a box, click the button to add it as new subset.

This is considerately complex than I thought, because getting the new subset is easy, but adding it to existing data and keep everything consistent is much more tricky, with many moving parts involved.

I made a lot of changes to code to make this change more systematic, and applying same method to other data set changing behavior (outlier removal, time subsetting etc). You can test the app now but I also need to test it thoroughly.
