### ISSUE TITLE
Visualization Page

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#88]
Currently, it is only possible to look at a maximum of 20 individuals at the same time. That means if a user has more than that, there is no way to see all of the data at once. I know the page can look cluttered, but I think it would be useful to have a "View all" option.

**Comment by xhdong-umd** [comment]
Select all button actually select all the individuals (it will not make sense to only select current page because that's the behavior when nothing was selected).

I didn't put a bigger number in page length list(I can easily add a 100 or 500) because the table will be quite long, the legend in plot will be very big, and the color mapping become useless.

The background always draw all points by default which can help to see the big picture too. 

I can add a bigger number in page length list if you want.

**Comment by NoonanM** [comment]
Select All works well. Sorry I missed that...

But it would still be nice for users to have the option to see all animals in the table if they want. I know the colour mapping gets bad, and the page gets really long, but the flexibility to go all the way to the full dataset would be useful.

**Comment by xhdong-umd** [comment]
The simplest way is to add a big number in page length list. We have limited space for buttons.

What will be a big enough number, 100, 500, 1000?

**Comment by xhdong-umd** [comment]
I added more options so that the page length can be one of (6, 10, 20, 100, 500). Hope this should be enough.
