### ISSUE TITLE
summary error after model fits

### ISSUE THREAD

**Issue by vickiedenicola** [ctmm-initiative/ctmmweb#96]
I'm getting a reproducible error at the end of the model selection step.

"Error: S3 method 'summary.character' not found"

<img width="1416" alt="Screen Shot 2019-06-12 at 11 41 36 AM" src="https://user-images.githubusercontent.com/32711183/59365890-5ad97900-8d07-11e9-818e-e212eee0df49.png">

This error is not happening when using ctmm from the command line. I am happy to add you in Movebank or send the file directly or via dropbox.

**Comment by xhdong-umd** [comment]
If you were running from local machine, do you see more error messages in R console?

If you were running from our website, you can click the "error message" button in left side bar to see if there is more information.

I saw this kind of error before, previously it's because the model fit didn't generate a valid result.

If you can send a dropbox link to my email(it should be in author field of the package description file) , I can have a look when I got time.

**Comment by vickiedenicola** [comment]
Thanks for the help.

I am running from local machine and just see:
[2019-06-12 16:16:54] Trying different models...
trying models on single animal with all but one cores
   user  system elapsed
279.276  44.814 190.337

The app oddly works if I run it from the website directly.  I have tried
uninstalling and reinstalling the packages (and restarting with clean
environment).

I'll send a dropbox link to the file via email.

**Comment by xhdong-umd** [comment]
I found the previous discussion #79. Do you have duplicated timestamps too?

**Comment by chfleming** [comment]
I do not believe there were any exact duplicates.

**Comment by xhdong-umd** [comment]
Issues #96, #97 are similar that there were some errors in model fitting and returned error instead of model results. Previously I was checking if any error happened in model fitting, but it seemed some parallel error was not fully captured in the error check.

Now I made the error checking more complete, any error like this should have a better error message, and user should be able to just change some option like turn off parallel or fine tune variagrams then fit model again.

If the problem still exist, user can try to save progress and report in github. For now without reproducible example I cannot further pin down the root cause of error.
